version: 4
jobs:
- name: build static web
  image: node:16.3.0
  commands:
  - git clone https://git.lain.fun/hana-web
  - '# npm config set registry https://registry.npm.taobao.org'
  - '# npm config get registry'
  - cd hana-web
  - ls
  - npm install
  - npm run build
  - ls
  retrieveSource: true
  cloneCredential: !DefaultCredential {}
  cpuRequirement: 250m
  memoryRequirement: 128m
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
